--@Autores: Jaime Garcia Frnacisco
--     	    Mora Magaña Jose David Divad
--@Fecha:   01/02/2021
--@Descripcion:  Inserts de la tabla incoveniente (34)

insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (67, 'Northfield', 71);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (68, 'Golden Leaf', 34);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (69, 'Forest Run', 86);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (70, 'Lighthouse Bay', 81);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (71, 'Hooker', 21);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (72, 'Manufacturers', 84);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (73, 'Del Mar', 82);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (74, 'Browning', 5);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (75, 'Arrowood', 4);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (76, 'Michigan', 32);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (77, 'David', 38);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (78, 'Hanover', 6);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (79, 'Golf View', 78);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (80, 'Loeprich', 31);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (81, 'Mandrake', 63);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (82, 'Mariners Cove', 39);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (83, 'Vera', 30);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (84, 'Maple Wood', 22);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (85, 'Blackbird', 8);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (86, 'Oak', 73);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (87, 'Lunder', 14);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (88, 'Maryland', 95);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (89, 'Green', 27);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (90, 'Ronald Regan', 97);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (91, 'Mifflin', 85);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (92, 'High Crossing', 50);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (93, 'Buhler', 32);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (94, 'Farragut', 90);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (95, 'Colorado', 53);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (96, 'Pennsylvania', 48);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (97, 'Main', 45);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (98, 'Petterle', 15);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (99, 'Amoth', 47);
insert into INCONVENIENTE (FALTA_CIVIL_ID, CENTRO_DETENCION, NIVEL_ALCOHOL) values (100, 'Glacier Hill', 86);


