--@Autores: Jaime Garcia Frnacisco
--     	    Mora Magaña Jose David Divad
--@Fecha:   01/02/2021
--@Descripcion:  Inserts de la tabla Tipo_trabajo_comunitario (9)

insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X001','BASURA','Recoger basura del piso');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X002','BARRER','Barrer las calles');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X003','COCINA','Apoyar en comedor comunitario');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X004','RECOLECTA','Recoletar viveres');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X005','ANCIANOS','Apoyar en un asilo');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X006','BILIOTECA','Apoyar en una biblioteca publica');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X007','BOMBEROS','Apoyar al cuerpo de bomberos');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X008','ARBOLES','Plantar arboles en parques y camellones');
insert into TIPO_TRABAJO_COMUNITARIO (TIPO_TRABAJO_COMUNITARIO_ID,CLAVE,NOMBRE,DESCRIPCION) values (TIPO_TRABAJO_COMUNITARIO_SEQ.NEXTVAL,'X009','TALLER','Apoyar en talleres publicos');

