--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      D
-- Project :      proyecto_er_v3.DM1
-- Author :       Dave
--
-- Date Created : Monday, February 01, 2021 19:01:37
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: LICENCIA 
--

CREATE TABLE LICENCIA(
    LICENCIA_ID       NUMBER(40, 0)    NOT NULL,
    FOLIO             VARCHAR2(40)     NOT NULL,
    PERMANENTE        VARCHAR2(3)      NOT NULL,
    VIGENCIA          DATE,
    VIGENCIA_FINAL    DATE             NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (LICENCIA_ID)
);



-- 
-- TABLE: CIUDADANO 
--

CREATE TABLE CIUDADANO(
    CIUDADANO_ID        NUMBER(40, 0)    NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    CORREO_E            VARCHAR2(40),
    DOMICILIO           VARCHAR2(40)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    APELLIDO_MATERNO    VARCHAR2(40),
    APELLIDO_PATERNO    VARCHAR2(40)     NOT NULL,
    LICENCIA_ID         NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (CIUDADANO_ID), 
    CONSTRAINT RefLICENCIA3 FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID)
);



-- 
-- TABLE: AUTO 
--

CREATE TABLE AUTO(
    AUTO_ID                VARCHAR2(40)     NOT NULL,
    PLACA                  VARCHAR2(40)     NOT NULL,
    TARJETA_CIRCULACION    VARCHAR2(40)     NOT NULL,
    VIGENCIA               DATE             NOT NULL,
    CIUDADANO_ID           NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (AUTO_ID), 
    CONSTRAINT RefCIUDADANO4 FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID)
)
;



-- 
-- TABLE: ESTATUS_FALTA 
--

CREATE TABLE ESTATUS_FALTA(
    ESTATUS_ID     VARCHAR2(40)    NOT NULL,
    DESCRIPCION    VARCHAR2(40)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (ESTATUS_ID)
)
;



-- 
-- TABLE: DISPOSITIVO 
--

CREATE TABLE DISPOSITIVO(
    DISPOSITIVO_ID    NUMBER(40, 0)    NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    TIPO              VARCHAR2(1)      NOT NULL,
    CONSTRAINT PK19 PRIMARY KEY (DISPOSITIVO_ID)
)
;



-- 
-- TABLE: FALTA_CIVIL 
--

CREATE TABLE FALTA_CIVIL(
    FALTACIV_ID       NUMBER(18, 0)    NOT NULL,
    CLIENTE           NUMBER(40, 0)    NOT NULL,
    NUMERO_FALTA      NUMBER(40, 0)    NOT NULL,
    FECHA_ACT         DATE             NOT NULL,
    TIPO_FALTA        CHAR(1)          NOT NULL,
    PUNTOS_NEG        NUMBER(18, 0)    NOT NULL,
    FECHA             DATE             NOT NULL,
    FECHA_LIM         DATE             NOT NULL,
    ESTATUS_ID        VARCHAR2(40)     NOT NULL,
    AUTO_ID           VARCHAR2(40)     NOT NULL,
    DISPOSITIVO_ID    NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (FALTACIV_ID), 
    CONSTRAINT RefAUTO9 FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO(AUTO_ID),
    CONSTRAINT RefESTATUS_FALTA11 FOREIGN KEY (ESTATUS_ID)
    REFERENCES ESTATUS_FALTA(ESTATUS_ID),
    CONSTRAINT RefDISPOSITIVO30 FOREIGN KEY (DISPOSITIVO_ID)
    REFERENCES DISPOSITIVO(DISPOSITIVO_ID)
)
;



-- 
-- TABLE: ALTO 
--

CREATE TABLE ALTO(
    FALTACIV_ID    NUMBER(18, 0)    NOT NULL,
    CRUCERO        VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (FALTACIV_ID), 
    CONSTRAINT RefFALTA_CIVIL14 FOREIGN KEY (FALTACIV_ID)
    REFERENCES FALTA_CIVIL(FALTACIV_ID)
)
;



-- 
-- TABLE: CIUDADANO_TELEFONO 
--

CREATE TABLE CIUDADANO_TELEFONO(
    CIUDADO_TEL_ID    NUMBER(38, 0)    NOT NULL,
    TELEFONO          VARCHAR2(10)     NOT NULL,
    CIUDADANO_ID      NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (CIUDADO_TEL_ID), 
    CONSTRAINT RefCIUDADANO1 FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID)
)
;



-- 
-- TABLE: DATOS_BIOMETRICOS 
--

CREATE TABLE DATOS_BIOMETRICOS(
    LICENCIA_HUELLA_ID    NUMBER(18, 0)    NOT NULL,
    FOTO                  BLOB             NOT NULL,
    FIRMA                 BLOB             NOT NULL,
    NUMERO_RENOVACION     NUMBER(40, 0)    NOT NULL,
    HUELLA                BLOB             NOT NULL,
    HUELLA_2              BLOB             NOT NULL,
    HUELLA_3              BLOB             NOT NULL,
    HUELLA_4              BLOB             NOT NULL,
    HUELLA_5              BLOB             NOT NULL,
    HUELLA6               BLOB             NOT NULL,
    HUELLA_7              BLOB             NOT NULL,
    HUELLA_8              BLOB             NOT NULL,
    HUELLA_9              BLOB             NOT NULL,
    HUELLA_10             BLOB             NOT NULL,
    LICENCIA_ID           NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (LICENCIA_HUELLA_ID), 
    CONSTRAINT RefLICENCIA2 FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID)
)
;



-- 
-- TABLE: FALTA_EVIDENCIA 
--

CREATE TABLE FALTA_EVIDENCIA(
    FALTA_EVI_ID    NUMBER(38, 0)    NOT NULL,
    FOTO_VIDEO      BLOB             NOT NULL,
    FALTACIV_ID     NUMBER(18, 0)    NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (FALTA_EVI_ID), 
    CONSTRAINT RefFALTA_CIVIL13 FOREIGN KEY (FALTACIV_ID)
    REFERENCES FALTA_CIVIL(FALTACIV_ID)
)
;



-- 
-- TABLE: HISTORICO_FALTA 
--

CREATE TABLE HISTORICO_FALTA(
    HISTORICO_FALTA_ID    NUMBER(18, 0)    NOT NULL,
    FECHA                 DATE             NOT NULL,
    FALTACIV_ID           NUMBER(18, 0)    NOT NULL,
    ESTATUS_ID            VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (HISTORICO_FALTA_ID), 
    CONSTRAINT RefFALTA_CIVIL10 FOREIGN KEY (FALTACIV_ID)
    REFERENCES FALTA_CIVIL(FALTACIV_ID),
    CONSTRAINT RefESTATUS_FALTA12 FOREIGN KEY (ESTATUS_ID)
    REFERENCES ESTATUS_FALTA(ESTATUS_ID)
)
;



-- 
-- TABLE: HISTPRICO_AUTO 
--

CREATE TABLE HISTPRICO_AUTO(
    HISTORICO_AUTO_ID    NUMBER(18, 0)    NOT NULL,
    FECHA                DATE             NOT NULL,
    AUTO_ID              VARCHAR2(40)     NOT NULL,
    CIUDADANO_ID         NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (HISTORICO_AUTO_ID), 
    CONSTRAINT RefAUTO5 FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO(AUTO_ID),
    CONSTRAINT RefCIUDADANO6 FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID)
)
;



-- 
-- TABLE: INCOVENIENTE 
--

CREATE TABLE INCOVENIENTE(
    FALTACIV_ID         NUMBER(18, 0)    NOT NULL,
    CENTRO_DETENCION    VARCHAR2(40)     NOT NULL,
    NIVEL_ALC           NUMBER(18, 0)    NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (FALTACIV_ID), 
    CONSTRAINT RefFALTA_CIVIL17 FOREIGN KEY (FALTACIV_ID)
    REFERENCES FALTA_CIVIL(FALTACIV_ID)
)
;



-- 
-- TABLE: ROBO 
--

CREATE TABLE ROBO(
    ROBO_ID           NUMBER(18, 0)    NOT NULL,
    ESTADO            VARCHAR2(40)     NOT NULL,
    FECHA             DATE             NOT NULL,
    LATITUD           NUMBER(40, 0),
    LONGITUD          NUMBER(40, 0),
    RECUPERADO        VARCHAR2(3),
    AUTO_ID           VARCHAR2(40)     NOT NULL,
    DISPOSITIVO_ID    NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (ROBO_ID), 
    CONSTRAINT RefAUTO18 FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO(AUTO_ID),
    CONSTRAINT RefDISPOSITIVO31 FOREIGN KEY (DISPOSITIVO_ID)
    REFERENCES DISPOSITIVO(DISPOSITIVO_ID)
)
;



-- 
-- TABLE: TIPO_TRABAJO_COMUNITARIO 
--

CREATE TABLE TIPO_TRABAJO_COMUNITARIO(
    TRABAJO_COMUNITARIO_ID    NUMBER(40, 0)    NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    NOMBRE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (TRABAJO_COMUNITARIO_ID)
)
;



-- 
-- TABLE: TRABAJO_COMUNITARIO 
--

CREATE TABLE TRABAJO_COMUNITARIO(
    TRABAJO_COMUNITARIO_ID    NUMBER(40, 0)    NOT NULL,
    HORAS                     NUMBER(18, 0)    NOT NULL,
    PUNTOS_RECUPERADOS        NUMBER(18, 0)    NOT NULL,
    LICENCIA_ID               NUMBER(40, 0)    NOT NULL,
    CONSTRAINT RefTIPO_TRABAJO_COMUNITARIO7 FOREIGN KEY (TRABAJO_COMUNITARIO_ID)
    REFERENCES TIPO_TRABAJO_COMUNITARIO(TRABAJO_COMUNITARIO_ID),
    CONSTRAINT RefLICENCIA8 FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID)
)
;



-- 
-- TABLE: VELOCIDAD 
--

CREATE TABLE VELOCIDAD(
    FALTACIV_ID            NUMBER(18, 0)    NOT NULL,
    LATITUD                NUMBER(40, 0)    NOT NULL,
    LONGITUD               NUMBER(40, 0)    NOT NULL,
    VELOCIDAD_MAX          NUMBER(18, 0)    NOT NULL,
    VELOCIDAD_REPORTADA    NUMBER(18, 0)    NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (FALTACIV_ID), 
    CONSTRAINT RefFALTA_CIVIL16 FOREIGN KEY (FALTACIV_ID)
    REFERENCES FALTA_CIVIL(FALTACIV_ID)
)
;



