--@Autores: Jaime Garcia Frnacisco
--     	    Mora Magaña Jose David Divad
--@Fecha:   01/02/2021
--@Descripcion: Creacion de las tablas 

-- 
-- TABLE: LICENCIA 
--
CREATE TABLE LICENCIA(
    LICENCIA_ID       NUMBER(40, 0)    NOT NULL,
    FOLIO             VARCHAR2(40)     NOT NULL,
    PERMANENTE        VARCHAR2(3)      NOT NULL,
    VIGENCIA          DATE,
    VIGENCIA_FINAL    DATE             NOT NULL,
    CONSTRAINT LICENCIA_PK PRIMARY KEY (LICENCIA_ID),
    CONSTRAINT LICENCIA_FOLIO_UK UNIQUE (FOLIO)
);

-- 
-- TABLE: CIUDADANO 
--
CREATE TABLE CIUDADANO(
    CIUDADANO_ID        NUMBER(10, 0)    NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    CORREO_E            VARCHAR2(40),
    DOMICILIO           VARCHAR2(40)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    APELLIDO_MATERNO    VARCHAR2(40),
    APELLIDO_PATERNO    VARCHAR2(40)     NOT NULL,
    LICENCIA_ID         NUMBER(40, 0)    NOT NULL,
    CONSTRAINT CIUDADANO_PK PRIMARY KEY (CIUDADANO_ID), 
    CONSTRAINT CIUDADANO_LICENCIA_ID_FK FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID)
);

-- 
-- TABLE: AUTO 
--
CREATE TABLE AUTO(
    AUTO_ID                NUMBER(10,0)     NOT NULL,
    PLACA                  VARCHAR2(40)     NOT NULL,
    TARJETA_CIRCULACION    VARCHAR2(40)     NOT NULL,
    VIGENCIA               DATE             NOT NULL,
    CIUDADANO_ID           NUMBER(40, 0)    NOT NULL,
    CONSTRAINT AUTO_PK PRIMARY KEY (AUTO_ID), 
    CONSTRAINT AUTO_PLACA_UK UNIQUE (PLACA),
    CONSTRAINT AUTO_CIUDADANO_FK FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID)
);

-- 
-- TABLE: ESTATUS_FALTA 
--
CREATE TABLE ESTATUS_FALTA(
    ESTATUS_ID     NUMBER(10,0)    NOT NULL,
    DESCRIPCION    VARCHAR2(40)    NOT NULL,
    CONSTRAINT ESTATUS_FALTA_PK PRIMARY KEY (ESTATUS_ID)
);

-- 
-- TABLE: DISPOSITIVO 
--
CREATE TABLE DISPOSITIVO(
    DISPOSITIVO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    TIPO              VARCHAR2(1)      NOT NULL,
    CONSTRAINT DISPOSITIVO_PK PRIMARY KEY (DISPOSITIVO_ID)
);

-- 
-- TABLE: FALTA_CIVIL 
--
CREATE TABLE FALTA_CIVIL(
    FALTA_CIVIL_ID    NUMBER(10, 0)    NOT NULL,
    CLIENTE           NUMBER(40, 0)    NOT NULL,
    NUMERO_FALTA      NUMBER(40, 0)    NOT NULL,
    FECHA_ACT         DATE             NOT NULL,
    TIPO_FALTA        CHAR(1)          NOT NULL,
    PUNTOS_NEG        NUMBER(18, 0)    NOT NULL,
    FECHA             DATE             NOT NULL,
    FECHA_LIM         DATE             NOT NULL,
    ESTATUS_ID        NUMBER(10,0)     NOT NULL,
    AUTO_ID           NUMBER(10,0)     NOT NULL,
    DISPOSITIVO_ID    NUMBER(40, 0)    NOT NULL,
    CONSTRAINT FALTA_CIVIL_PK PRIMARY KEY (FALTA_CIVIL_ID), 
    CONSTRAINT FALTA_CIVIL_AUTO_ID_KF FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO(AUTO_ID),
    CONSTRAINT FALTA_CIVIL_ESTATUS_ID_FK FOREIGN KEY (ESTATUS_ID)
    REFERENCES ESTATUS_FALTA(ESTATUS_ID),
    CONSTRAINT FALTA_CIVIL_DISPOSITIVO_ID_FK FOREIGN KEY (DISPOSITIVO_ID)
    REFERENCES DISPOSITIVO(DISPOSITIVO_ID),
    CONSTRAINT FALTA_CIVIL_TIPO_FALTA_CK CHECK (TIPO_FALTA IN ('A','I','V'))
);

-- 
-- TABLE: ALTO 
--
CREATE TABLE ALTO(
    FALTA_CIVIL_ID    NUMBER(10, 0)    NOT NULL,
    CRUCERO           VARCHAR2(40)     NOT NULL,
    CONSTRAINT ALTO_PK PRIMARY KEY (FALTA_CIVIL_ID), 
    CONSTRAINT ALTO_FALTA_CIVIL_ID_FK FOREIGN KEY (FALTA_CIVIL_ID)
    REFERENCES FALTA_CIVIL(FALTA_CIVIL_ID)
);

-- 
-- TABLE: CIUDADANO_TELEFONO 
--
CREATE TABLE CIUDADANO_TELEFONO(
    CIUDADO_TEL_ID    NUMBER(10, 0)    NOT NULL,
    TELEFONO          VARCHAR2(10)     NOT NULL,
    CIUDADANO_ID      NUMBER(40, 0)    NOT NULL,
    CONSTRAINT CIUDADANO_TELEFONO_PK PRIMARY KEY (CIUDADO_TEL_ID), 
    CONSTRAINT CIUDADANO_TELEFONO_CIUDADANO_ID_FK FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID)
);

-- 
-- TABLE: DATOS_BIOMETRICOS 
--
CREATE TABLE DATOS_BIOMETRICOS(
    DATOS_BIOMETRICOS_ID  NUMBER(10, 0)    NOT NULL,
    FOTO                  BLOB             NOT NULL,
    FIRMA                 BLOB             NOT NULL,
    NUMERO_RENOVACION     NUMBER(40, 0)    NOT NULL,
    HUELLA                BLOB             NOT NULL,
    HUELLA_2              BLOB             NOT NULL,
    HUELLA_3              BLOB             NOT NULL,
    HUELLA_4              BLOB             NOT NULL,
    HUELLA_5              BLOB             NOT NULL,
    HUELLA6               BLOB             NOT NULL,
    HUELLA_7              BLOB             NOT NULL,
    HUELLA_8              BLOB             NOT NULL,
    HUELLA_9              BLOB             NOT NULL,
    HUELLA_10             BLOB             NOT NULL,
    LICENCIA_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT DATOS_BIOMETRICOS_PK PRIMARY KEY (DATOS_BIOMETRICOS_ID), 
    CONSTRAINT DATOS_BIOMETRICOS_LICENCIA_ID_FK FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID)
);

-- 
-- TABLE: FALTA_EVIDENCIA 
--
CREATE TABLE FALTA_EVIDENCIA(
    FALTA_EVIDENCIA_ID    NUMBER(10, 0)    NOT NULL,
    FOTO_VIDEO            BLOB             NOT NULL,
    FALTA_CIVIL_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT FALTA_EVIDENCIA PRIMARY KEY (FALTA_EVIDENCIA_ID), 
    CONSTRAINT FALTA_EVIDENCIA_FALTA_CIVIL_ID_FK FOREIGN KEY (FALTA_CIVIL_ID)
    REFERENCES FALTA_CIVIL(FALTA_CIVIL_ID)
);

-- 
-- TABLE: HISTORICO_FALTA 
--
CREATE TABLE HISTORICO_FALTA(
    HISTORICO_FALTA_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                 DATE             NOT NULL,
    FALTA_CIVIL_ID        NUMBER(10, 0)    NOT NULL,
    ESTATUS_ID            NUMBER(10,0)     NOT NULL,
    CONSTRAINT HISTORICO_FALTA_PK PRIMARY KEY (HISTORICO_FALTA_ID), 
    CONSTRAINT HISTORICO_FALTA_FALTA_CIVIL_ID_FK FOREIGN KEY (FALTA_CIVIL_ID)
    REFERENCES FALTA_CIVIL(FALTA_CIVIL_ID),
    CONSTRAINT HISTORICO_FALTA_ESTATUS_ID_FK FOREIGN KEY (ESTATUS_ID)
    REFERENCES ESTATUS_FALTA(ESTATUS_ID)
);

-- 
-- TABLE: HISTPRICO_AUTO 
--
CREATE TABLE HISTPRICO_AUTO(
    HISTORICO_AUTO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                DATE             NOT NULL,
    AUTO_ID              NUMBER(10,0)     NOT NULL,
    CIUDADANO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTPRICO_AUTO_PK PRIMARY KEY (HISTORICO_AUTO_ID), 
    CONSTRAINT HISTORICO_AUTO_ID_FK FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO(AUTO_ID),
    CONSTRAINT HISTORICO_AUTO_CIUDADANO_ID FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID)
);

-- 
-- TABLE: INCOVENIENTE 
--
CREATE TABLE INCOVENIENTE(
    FALTA_CIVIL_ID      NUMBER(10, 0)    NOT NULL,
    CENTRO_DETENCION    VARCHAR2(40)     NOT NULL,
    NIVEL_ALC           NUMBER(18, 0)    NOT NULL,
    CONSTRAINT INCOVENIENTE_PK PRIMARY KEY (FALTA_CIVIL_ID), 
    CONSTRAINT INCOVENIENTE_FALTA_CIVIL_ID_PK FOREIGN KEY (FALTA_CIVIL_ID)
    REFERENCES FALTA_CIVIL(FALTA_CIVIL_ID)
);

-- 
-- TABLE: ROBO 
--
CREATE TABLE ROBO(
    ROBO_ID           NUMBER(10, 0)    NOT NULL,
    ESTADO            VARCHAR2(40)     NOT NULL,
    FECHA             DATE             NOT NULL,
    LATITUD           NUMBER(40, 0),
    LONGITUD          NUMBER(40, 0),
    RECUPERADO        VARCHAR2(3),
    AUTO_ID           NUMBER(10,0)     NOT NULL,
    DISPOSITIVO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ROBO_PK PRIMARY KEY (ROBO_ID), 
    CONSTRAINT ROBO_AUTO_ID_FK FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO(AUTO_ID),
    CONSTRAINT ROBO_DISPOSITIVO_ID_FK FOREIGN KEY (DISPOSITIVO_ID)
    REFERENCES DISPOSITIVO(DISPOSITIVO_ID)
);

-- 
-- TABLE: TIPO_TRABAJO_COMUNITARIO 
--
CREATE TABLE TIPO_TRABAJO_COMUNITARIO(
    TIPO_TRABAJO_COMUNITARIO_ID     NUMBER(10, 0)    NOT NULL,
    CLAVE                           VARCHAR2(40)     NOT NULL,
    NOMBRE                          VARCHAR2(40)     NOT NULL,
    DESCRIPCION                     VARCHAR2(40)     NOT NULL,
    CONSTRAINT TIPO_TRABAJO_COMUNITARIO_PK PRIMARY KEY (TIPO_TRABAJO_COMUNITARIO_ID)
);

-- 
-- TABLE: TRABAJO_COMUNITARIO 
--
CREATE TABLE TRABAJO_COMUNITARIO(
    TRABAJO_COMUNITARIO_ID          NUMBER(10, 0)    NOT NULL,
    TIPO_TRABAJO_COMUNITARIO_ID     NUMBER(10, 0)    NOT NULL,
    HORAS                           NUMBER(18, 0)    NOT NULL,
    PUNTOS_RECUPERADOS              NUMBER(18, 0)    NOT NULL,
    LICENCIA_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT TRABAJO_COMUNITARIO_PK PRIMARY KEY (TRABAJO_COMUNITARIO_ID),
    CONSTRAINT TRABAJO_COMUNITARIO_TIPO_TRABAJO_COMUNITARIO_ID_FK FOREIGN KEY (TIPO_TRABAJO_COMUNITARIO_ID)
    REFERENCES TIPO_TRABAJO_COMUNITARIO(TRABAJO_COMUNITARIO_ID),
    CONSTRAINT TRABAJO_COMUNITARIO_LICENCIA_ID_FK FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID)
);

-- 
-- TABLE: VELOCIDAD 
--
CREATE TABLE VELOCIDAD(
    FALTA_CIVIL_ID         NUMBER(10, 0)    NOT NULL,
    LATITUD                NUMBER(40, 0)    NOT NULL,
    LONGITUD               NUMBER(40, 0)    NOT NULL,
    VELOCIDAD_MAX          NUMBER(18, 0)    NOT NULL,
    VELOCIDAD_REPORTADA    NUMBER(18, 0)    NOT NULL,
    CONSTRAINT VELOCIDAD_PK PRIMARY KEY (FALTA_CIVIL_ID), 
    CONSTRAINT VELOCIDAD_FALTA_CIVIL_ID_FK FOREIGN KEY (FALTA_CIVIL_ID)
    REFERENCES FALTA_CIVIL(FALTA_CIVIL_ID)
);

