--@Autores: Jaime Garcia Frnacisco
--     	    Mora Magaña Jose David Divad
--@Fecha:   01/02/2021
--@Descripcion: Creacion de las tablas del modulo CIUDADANOS y su secuencia

connect admin_ciudadanos/ciudadanos

-- 
-- TABLE: LICENCIA
--
CREATE SEQUENCE LICENCIA_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE LICENCIA(
    LICENCIA_ID       NUMBER(20, 0)    NOT NULL,
    FOLIO             NUMBER(8,0)      NOT NULL,
    PERMANENTE        VARCHAR2(3)      NOT NULL,
    VIGENCIA_INICIAL  DATE,
    VIGENCIA_FINAL    DATE             NOT NULL,
    CONSTRAINT LICENCIA_PK PRIMARY KEY (LICENCIA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX LICENCIA_PK ON LICENCIA(LICENCIA_ID)
        TABLESPACE TSI_CIUDADANOS)
) TABLESPACE TST_CIUDADANOS;

-- 
-- TABLE: CIUDADANO
--
CREATE SEQUENCE CIUDADANO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE CIUDADANO(
    CIUDADANO_ID        NUMBER(10, 0)    NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    CORREO_ELECTRONICO  VARCHAR2(40),
    DOMICILIO           VARCHAR2(40)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    APELLIDO_MATERNO    VARCHAR2(40),
    APELLIDO_PATERNO    VARCHAR2(40)     NOT NULL,
    LICENCIA_ID         NUMBER(20, 0)    NOT NULL, 
    CONSTRAINT CIUDADANO_LICENCIA_ID_FK FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID),
    CONSTRAINT CIUDADANO_PK PRIMARY KEY (CIUDADANO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CIUDADANO_PK ON CIUDADANO(CIUDADANO_ID)
        TABLESPACE TSI_CIUDADANOS)
) TABLESPACE TST_CIUDADANOS;

-- 
-- TABLE: AUTO
--
CREATE SEQUENCE AUTO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE AUTO(
    AUTO_ID                NUMBER(10,0)     NOT NULL,
    PLACA                  VARCHAR2(40)     NOT NULL,
    TARJETA_CIRCULACION    VARCHAR2(40)     NOT NULL,
    VIGENCIA               DATE             NOT NULL,
    CIUDADANO_ID           NUMBER(20, 0)    NOT NULL, 
    CONSTRAINT AUTO_CIUDADANO_FK FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID),
    CONSTRAINT AUTO_PK PRIMARY KEY (AUTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX AUTO_PK ON AUTO(AUTO_ID)
        TABLESPACE TSI_CIUDADANOS)
) TABLESPACE TST_CIUDADANOS;

-- 
-- TABLE: CIUDADANO_TELEFONO
--
CREATE SEQUENCE CIUDADANO_TELEFONO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE CIUDADANO_TELEFONO(
    CIUDADO_TELEFONO_ID    NUMBER(10, 0)    NOT NULL,
    TELEFONO               VARCHAR2(10)     NOT NULL,
    CIUDADANO_ID           NUMBER(20, 0)    NOT NULL,
    CONSTRAINT CIUDADANO_TELEFONO_CIUDADANO_ID_FK FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID),
    CONSTRAINT CIUDADANO_TELEFONO_PK PRIMARY KEY (CIUDADO_TELEFONO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CIUDADANO_TELEFONO_PK ON CIUDADANO_TELEFONO(CIUDADO_TELEFONO_ID)
        TABLESPACE TSI_TRAMITES)
) TABLESPACE TST_CIUDADANOS;

-- 
-- TABLE: DATOS_BIOMETRICOS
--
CREATE SEQUENCE DATOS_BIOMETRICOS_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE DATOS_BIOMETRICOS(
    DATOS_BIOMETRICOS_ID  NUMBER(10, 0)    NOT NULL,
    FOTO                  BLOB             NOT NULL,
    FIRMA                 BLOB             NOT NULL,
    NUMERO_RENOVACION     NUMBER(20, 0)    NOT NULL,
    HUELLA_1              BLOB             NOT NULL,
    HUELLA_2              BLOB             NOT NULL,
    HUELLA_3              BLOB             NOT NULL,
    HUELLA_4              BLOB             NOT NULL,
    HUELLA_5              BLOB             NOT NULL,
    HUELLA_6              BLOB             NOT NULL,
    HUELLA_7              BLOB             NOT NULL,
    HUELLA_8              BLOB             NOT NULL,
    HUELLA_9              BLOB             NOT NULL,
    HUELLA_10             BLOB             NOT NULL,
    LICENCIA_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT DATOS_BIOMETRICOS_LICENCIA_ID_FK FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID),
    CONSTRAINT DATOS_BIOMETRICOS_PK PRIMARY KEY (DATOS_BIOMETRICOS_ID)
    USING INDEX (
        CREATE UNIQUE INDEX DATOS_BIOMETRICOS_PK ON DATOS_BIOMETRICOS(DATOS_BIOMETRICOS_ID)
        TABLESPACE TSI_CIUDADANOS)
) TABLESPACE TST_CIUDADANOS
LOB (FOTO,FIRMA,HUELLA_1,HUELLA_2,HUELLA_3,HUELLA_4,HUELLA_5,HUELLA_6,HUELLA_7,HUELLA_8,HUELLA_9,HUELLA_10) STORE AS SECUREFILE (TABLESPACE COMUN_BLOB);

-- 
-- TABLE: HISTORICO_AUTO
--
CREATE SEQUENCE HISTORICO_AUTO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE HISTORICO_AUTO(
    HISTORICO_AUTO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                DATE             NOT NULL,
    AUTO_ID              NUMBER(10,0)     NOT NULL,
    CIUDADANO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_AUTO_ID_FK FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO(AUTO_ID),
    CONSTRAINT HISTORICO_AUTO_CIUDADANO_ID FOREIGN KEY (CIUDADANO_ID)
    REFERENCES CIUDADANO(CIUDADANO_ID),
    CONSTRAINT HISTPRICO_AUTO_PK PRIMARY KEY (HISTORICO_AUTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX HISTORICO_AUTO_PK ON HISTORICO_AUTO(HISTORICO_AUTO_ID)
        TABLESPACE TSI_CIUDADANOS)
) TABLESPACE TST_CIUDADANOS;

-- 
-- TABLE: TIPO_TRABAJO_COMUNITARIO
--
CREATE SEQUENCE TIPO_TRABAJO_COMUNITARIO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE TIPO_TRABAJO_COMUNITARIO(
    TIPO_TRABAJO_COMUNITARIO_ID     NUMBER(10, 0)    NOT NULL,
    CLAVE                           VARCHAR2(40)     NOT NULL,
    NOMBRE                          VARCHAR2(40)     NOT NULL,
    DESCRIPCION                     VARCHAR2(40)     NOT NULL,
    CONSTRAINT TIPO_TRABAJO_COMUNITARIO_PK PRIMARY KEY (TIPO_TRABAJO_COMUNITARIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX TIPO_TRABAJO_COMUNITARIO_PK ON TIPO_TRABAJO_COMUNITARIO(TIPO_TRABAJO_COMUNITARIO_ID)
        TABLESPACE TSI_CIUDADANOS)
) TABLESPACE TST_CIUDADANOS;

-- 
-- TABLE: TRABAJO_COMUNITARIO
--
CREATE SEQUENCE TRABAJO_COMUNITARIO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE;

CREATE TABLE TRABAJO_COMUNITARIO(
    TRABAJO_COMUNITARIO_ID          NUMBER(10, 0)    NOT NULL,
    TIPO_TRABAJO_COMUNITARIO_ID     NUMBER(10, 0)    NOT NULL,
    HORAS                           NUMBER(18, 0)    NOT NULL,
    PUNTOS_RECUPERADOS              NUMBER(18, 0)    NOT NULL,
    LICENCIA_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT TRABAJO_COMUNITARIO_TIPO_TRABAJO_COMUNITARIO_ID_FK FOREIGN KEY (TIPO_TRABAJO_COMUNITARIO_ID)
    REFERENCES TIPO_TRABAJO_COMUNITARIO(TIPO_TRABAJO_COMUNITARIO_ID),
    CONSTRAINT TRABAJO_COMUNITARIO_LICENCIA_ID_FK FOREIGN KEY (LICENCIA_ID)
    REFERENCES LICENCIA(LICENCIA_ID),
    CONSTRAINT TRABAJO_COMUNITARIO_PK PRIMARY KEY (TRABAJO_COMUNITARIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX TRABAJO_COMUNITARIO_PK ON TRABAJO_COMUNITARIO(TRABAJO_COMUNITARIO_ID)
        TABLESPACE TSI_CIUDADANOS)
) TABLESPACE TST_CIUDADANOS;

