--@Autores: Jaime Garcia Frnacisco
--     	    Mora Magaña Jose David Divad
--@Fecha:   01/02/2021
--@Descripcion: Creacion de los indices necesarios para el modulo CIUDADANOS

CREATE UNIQUE INDEX CIUDADANO_CURP_UK
    ON CIUDADANO(CURP)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX TRABAJO_TIPO_TC_ID_IX
    ON TRABAJO_COMUNITARIO(TIPO_TRABAJO_COMUNITARIO_ID)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX TRABAJO_LICENCIA_ID_IX
    ON TRABAJO_COMUNITARIO(LICENCIA_ID)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX CIUDADANO_TEL_CIUDADANO_ID_IX
    ON CIUDADANO_TELEFONO(CIUDADANO_ID)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX CIUDADANO_LICENCIA_ID_IX
    ON CIUDADANO(LICENCIA_ID)
TABLESPACE TSI_CIUDADANOS;

CREATE UNIQUE INDEX CIUDADANO_CURP_UK
    ON CIUDADANO(CURP)
TABLESPACE TSI_CIUDADANOS;

CREATE UNIQUE INDEX LICENCIA_FOLIO_UK
    ON LICENCIA(FOLIO)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX DATOS_BIOMETRICOS_LICENCIA_ID_IX
    ON DATOS_BIOMETRICOS(LICENCIA_ID)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX AUTO_CIUDADANO_ID_IX
    ON AUTO(CIUDADANO_ID)
TABLESPACE TSI_CIUDADANOS;

CREATE UNIQUE INDEX AUTO_PLACA_UK
    ON AUTO(PLACA)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX HISTORICO_FALTA_FALTA_CIVIL_ID_IX
    ON HISTORICO_FALTA(AUTO_ID)
TABLESPACE TSI_CIUDADANOS;

CREATE INDEX HISTORICO_FALTA_ESTATUS_FALTA_ID_IX
    ON HISTORICO_FALTA(CIUDADANO_ID)
TABLESPACE TSI_CIUDADANOS;