--@Autores: Jaime Garcia Frnacisco
--     	    Mora Magaña Jose David Divad
--@Fecha:   01/02/2021
--@Descripcion: Creacion de los indices necesarios para el modulo TRAMITES

CREATE INDEX FALTA_CIVIL_ESTATUS_FALTA_ID_IX
    ON FALTA_CIVIL(ESTATUS_FALTA_ID)
TABLESPACE TSI_TRAMITES;

CREATE INDEX FALTA_CIVIL_AUTO_ID_IX
    ON FALTA_CIVIL(AUTO_ID)
TABLESPACE TSI_TRAMITES;

CREATE INDEX FALTA_CIVIL_DISPOSITIVO_ID_IX
    ON FALTA_CIVIL(DISPOSITIVO_ID)
TABLESPACE TSI_TRAMITES;

CREATE UNIQUE INDEX FALTA_CIVIL_CLIENTE_NUMERO_UX
    ON FALTA_CIVIL(CLIENTE, NUMERO_FALTA)
TABLESPACE TSI_TRAMITES;

CREATE INDEX HISTORICO_FALTA_FALTA_CIVIL_ID_IX
    ON HISTORICO_FALTA(FALTA_CIVIL_ID)
TABLESPACE TSI_TRAMITES;

CREATE INDEX HISTORICO_FALTA_ESTATUS_FALTA_ID_IX
    ON HISTORICO_FALTA(ESTATUS_FALTA_ID)
TABLESPACE TSI_TRAMITES;

CREATE UNIQUE INDEX DISPOSITIVO_CLAVE_UK
    ON DISPOSITIVO(CLAVE)
TABLESPACE TSI_TRAMITES;

CREATE INDEX FALTA_EVIDENCIA_FALTA_CIVIL_ID_IX
    ON FALTA_EVIDENCIA(FALTA_CIVIL_ID)
TABLESPACE TSI_TRAMITES;

CREATE INDEX ROBO_AUTO_ID_IX
    ON ROBO(AUTO_ID)
TABLESPACE TSI_TRAMITES;

CREATE INDEX ROBO_DISPOSITIVO_ID_IX
    ON ROBO(DISPOSITIVO_ID)
TABLESPACE TSI_TRAMITES;
